### ISSUE TITLE
Handle "non-string" metadata field types

### ISSUE THREAD

**Issue by mrk-te** [Codein-Labs/ibexa-seo-toolkit#4]
Can we provide a solution to source metadata from "non-string" field types like boolean or image ?

Two use cases : 

* Boolean field to add a "robots noindex, nofollow" tag by checking a box. Might be "multiple" like one checkbox for "index", one for follow
* Render an `ezimage` field with the configured alias as an `og:image` meta tag

**Comment by RudyCodein** [comment]
#14

**Comment by axelveber** [comment]
Merged, thank you @RudyCodein
